# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-06-17 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='restaurant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('lat', models.CharField(max_length=1000)),
                ('long', models.CharField(max_length=1000)),
                ('url', models.CharField(max_length=1000)),
                ('rating', models.CharField(blank=True, max_length=1000, null=True)),
                ('address', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rest_name', models.CharField(max_length=1000)),
                ('cust_name', models.CharField(max_length=1000)),
                ('content', models.CharField(max_length=1000)),
            ],
        ),
    ]
