# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-06-17 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zomato_scrapers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.CharField(max_length=90000),
        ),
    ]
